{% set name = "opencensus-context" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opencensus-context-{{ version }}.tar.gz
  sha256: a03108c3c10d8c80bb5ddf5c8a1f033161fa61972a9917f9b9b3a18517f0088c

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - contextvars  # [py<=3.7]

test:
  imports:
    - opencensus
    - opencensus.common.runtime_context
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/census-instrumentation/opencensus-python/tree/master/context/opencensus-context
  license: Apache-2.0
  license_file: LICENSE
  summary: The OpenCensus Runtime Context.
  description: |
    The OpenCensus Runtime Context provides in-process context propagation.
    By default, thread local storage is used for Python 2.7, 3.4 and 3.5;
    contextvars is used for Python >= 3.6, which provides asyncio support.
    
    PyPI: [https://pypi.org/project/opencensus-context/](https://pypi.org/project/opencensus-context/)
    
  doc_url: https://github.com/census-instrumentation/opencensus-python/tree/master/context/opencensus-context/examples
  dev_url: https://github.com/census-instrumentation/opencensus-python/tree/master/context/opencensus-context

extra:
  recipe-maintainers:
    - basnijholt
    - dhirschfeld
    - sugatoray
